config/routes.rb
ActiveGallery::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pages

  resources :pieces

  resources :galleries

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/piece.rb
class Piece < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < InheritedResources::Base
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
end

app/controllers/pieces_controller.rb
class PiecesController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.text_field :image_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Author</th>
      <th>Image file</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @galleries.each do |gallery| %>
      <tr>
        <td><%= gallery.title %></td>
        <td><%= gallery.description %></td>
        <td><%= gallery.author %></td>
        <td><%= gallery.image_file %></td>
        <td><%= link_to 'Show', gallery %></td>
        <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
        <td><%= link_to 'Destroy', gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gallery.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @gallery.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @gallery.author %>
</p>

<p>
  <strong>Image file:</strong>
  <%= @gallery.image_file %>
</p>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ActiveGallery</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :seo %><br>
    <%= f.text_area :seo %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :view_template %><br>
    <%= f.text_field :view_template %>
  </div>
  <div class="field">
    <%= f.label :layout_template %><br>
    <%= f.text_field :layout_template %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug %>
  </div>
  <div class="field">
    <%= f.label :link_url %><br>
    <%= f.text_field :link_url %>
  </div>
  <div class="field">
    <%= f.label :path %><br>
    <%= f.text_field :path %>
  </div>
  <div class="field">
    <%= f.label :visible %><br>
    <%= f.check_box :visible %>
  </div>
  <div class="field">
    <%= f.label :deleted %><br>
    <%= f.check_box :deleted %>
  </div>
  <div class="field">
    <%= f.label :deletable %><br>
    <%= f.check_box :deletable %>
  </div>
  <div class="field">
    <%= f.label :draft %><br>
    <%= f.check_box :draft %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :lft %><br>
    <%= f.number_field :lft %>
  </div>
  <div class="field">
    <%= f.label :rgt %><br>
    <%= f.number_field :rgt %>
  </div>
  <div class="field">
    <%= f.label :depth %><br>
    <%= f.number_field :depth %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Seo</th>
      <th>Body</th>
      <th>View template</th>
      <th>Layout template</th>
      <th>Slug</th>
      <th>Link url</th>
      <th>Path</th>
      <th>Visible</th>
      <th>Deleted</th>
      <th>Deletable</th>
      <th>Draft</th>
      <th>Position</th>
      <th>Parent</th>
      <th>Lft</th>
      <th>Rgt</th>
      <th>Depth</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.seo %></td>
        <td><%= page.body %></td>
        <td><%= page.view_template %></td>
        <td><%= page.layout_template %></td>
        <td><%= page.slug %></td>
        <td><%= page.link_url %></td>
        <td><%= page.path %></td>
        <td><%= page.visible %></td>
        <td><%= page.deleted %></td>
        <td><%= page.deletable %></td>
        <td><%= page.draft %></td>
        <td><%= page.position %></td>
        <td><%= page.parent_id %></td>
        <td><%= page.lft %></td>
        <td><%= page.rgt %></td>
        <td><%= page.depth %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Seo:</strong>
  <%= @page.seo %>
</p>

<p>
  <strong>Body:</strong>
  <%= @page.body %>
</p>

<p>
  <strong>View template:</strong>
  <%= @page.view_template %>
</p>

<p>
  <strong>Layout template:</strong>
  <%= @page.layout_template %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Link url:</strong>
  <%= @page.link_url %>
</p>

<p>
  <strong>Path:</strong>
  <%= @page.path %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @page.visible %>
</p>

<p>
  <strong>Deleted:</strong>
  <%= @page.deleted %>
</p>

<p>
  <strong>Deletable:</strong>
  <%= @page.deletable %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @page.draft %>
</p>

<p>
  <strong>Position:</strong>
  <%= @page.position %>
</p>

<p>
  <strong>Parent:</strong>
  <%= @page.parent_id %>
</p>

<p>
  <strong>Lft:</strong>
  <%= @page.lft %>
</p>

<p>
  <strong>Rgt:</strong>
  <%= @page.rgt %>
</p>

<p>
  <strong>Depth:</strong>
  <%= @page.depth %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pieces/_form.html.erb
<%= form_for(@piece) do |f| %>
  <% if @piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% @piece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gallery_id %><br>
    <%= f.number_field :gallery_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :dimensions %><br>
    <%= f.text_field :dimensions %>
  </div>
  <div class="field">
    <%= f.label :completed_date %><br>
    <%= f.datetime_select :completed_date %>
  </div>
  <div class="field">
    <%= f.label :medium %><br>
    <%= f.text_field :medium %>
  </div>
  <div class="field">
    <%= f.label :image_file %><br>
    <%= f.text_field :image_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<h1>Editing piece</h1>

<%= render 'form' %>

<%= link_to 'Show', @piece %> |
<%= link_to 'Back', pieces_path %>

app/views/pieces/index.html.erb
<h1>Listing pieces</h1>

<table>
  <thead>
    <tr>
      <th>Gallery</th>
      <th>Type</th>
      <th>Title</th>
      <th>Description</th>
      <th>Dimensions</th>
      <th>Completed date</th>
      <th>Medium</th>
      <th>Image file</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pieces.each do |piece| %>
      <tr>
        <td><%= piece.gallery_id %></td>
        <td><%= piece.type %></td>
        <td><%= piece.title %></td>
        <td><%= piece.description %></td>
        <td><%= piece.dimensions %></td>
        <td><%= piece.completed_date %></td>
        <td><%= piece.medium %></td>
        <td><%= piece.image_file %></td>
        <td><%= link_to 'Show', piece %></td>
        <td><%= link_to 'Edit', edit_piece_path(piece) %></td>
        <td><%= link_to 'Destroy', piece, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Piece', new_piece_path %>

app/views/pieces/new.html.erb
<h1>New piece</h1>

<%= render 'form' %>

<%= link_to 'Back', pieces_path %>

app/views/pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gallery:</strong>
  <%= @piece.gallery_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @piece.type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @piece.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @piece.description %>
</p>

<p>
  <strong>Dimensions:</strong>
  <%= @piece.dimensions %>
</p>

<p>
  <strong>Completed date:</strong>
  <%= @piece.completed_date %>
</p>

<p>
  <strong>Medium:</strong>
  <%= @piece.medium %>
</p>

<p>
  <strong>Image file:</strong>
  <%= @piece.image_file %>
</p>

<%= link_to 'Edit', edit_piece_path(@piece) %> |
<%= link_to 'Back', pieces_path %>